version: "3"
services:
  web:
    build: ./docker/log_watcher
    image: ngnix_ingest
    ports:
      - 4000-4010:80
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./docker/log_watcher/ingest_api.conf:/etc/nginx/conf.d/default.conf
      - ./docker/log_watcher/nginx.conf:/etc/nginx/nginx.conf
      - ./log_watcher/entrypoint.sh:/entrypoint.sh
      - ./log_watcher/:/home/app/

  aggregator:
    build: ./docker/aggregator
    image: aggregator
    container_name: aggregator
    ports:
      - 5000:5000
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./aggregator/entrypoint.sh:/entrypoint.sh
      - ./aggregator/:/home/app/