version: "3"
services:
  web:
    build: ./docker
    image: ngnix_ingest
    container_name: ngnix_ingest
    ports:
      - 4000:80
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./docker/ingest_api.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./entrypoint.sh:/entrypoint.sh
      - ./:/home/app/